Fix compile errors in qev
src/qev/qev.cpp:42:11: error: ‘virtual QSize Widget::sizeHint() const’
  can be marked override [-Werror=suggest-override]
   42 |     QSize sizeHint() const { return QSize(20, 20); }
      |           ^~~~~~~~
src/qev/qev.cpp:43:10: error: ‘virtual bool Widget::event(QEvent*)’
  can be marked override [-Werror=suggest-override]
   43 |     bool event(QEvent *e) {
      |          ^~~~~
src/qev/qev.cpp: In function ‘int main(int, char**)’:
src/qev/qev.cpp:56:11: error: aggregate ‘QFile fout’ has incomplete type
  and cannot be defined
   56 |     QFile fout;
      |           ^~~~

Change-Id: Ie6f9ffe76d1a665bd35a9cb6ca1ec36f660d9a70
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>
(cherry picked from commit a7689b41c722e8d001a94ee730c0f09f43a10ef5)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>