CMake: Link to Core library in linguist tests to get -fPIC flags
qt6_add_library does not automatically link to Qt6::Core or
Qt6::Platform, which means the created target does not inherit any
possible -fPIC flags that might be needed.

Starting with 22029a76c37d8d670479d523684a84f7966ed434 in qtbase,
this causes the following error in translations units that include
qcompilerdetection.h:

 include/QtCore/qcompilerdetection.h:1272:4: error: #error "You must
 build your code with position independent code if Qt was configured
 with -reduce-relocations. " "Compile your code with -fPIC (and not
 with -fPIE)."

We include qcompilerdetection.h in rcc generated cpp files, and that
caused the above error for the resources generated for the i18n test
libraries.

Fix that by explicitly linking to Qt6::Core.

We will probably want to change the implementation of qt6_add_library
to at least link to Qt6::Platform.

Fixes: QTBUG-117970
Change-Id: I2181df2c7c8818fcb198cc4e8f9eee304fc6bc90
Reviewed-by: Qt CI Bot <qt_ci_bot@qt-project.org>
Reviewed-by: Ville Voutilainen <ville.voutilainen@qt.io>