Qt Designer: Fix CMake Unity (Jumbo) build errors related to UI forms
Add QT_PREPEND_NAMESPACE(Ui), fixing:

src/designer/src/lib/shared/formlayoutmenu.cpp:96:9: error: FormLayoutRowDialog namespace qdesigner_internal::Ui does not name a type
   96 |     Ui::FormLayoutRowDialog m_ui;

Task-number: QTBUG-109394
Change-Id: If2939f1750f8406beda587e3818daa0d3a15def9
Reviewed-by: Jarek Kobus <jaroslaw.kobus@qt.io>
(cherry picked from commit eb46711c2000c11c5daf8c3704589c486c1141d2)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>