CMake: Require libclang 16 for lupdate on MSVC version 1939
The headers of this MSVC version require at least libclang 16, and
running clang-based lupdate will fail with such an error:

error: static assertion failed: error STL1000: Unexpected compiler
version, expected Clang 16.0.0 or newer. _EMIT_STL_ERROR(STL1000,
"Unexpected compiler version, expected Clang 16.0.0 or newer.");

Task-number: QTBUG-123611
Change-Id: I7006a72bd522b6ba7b6368fb5e99fe49b95c845c
Reviewed-by:  Alexey Edelev <alexey.edelev@qt.io>
(cherry picked from commit 9746a55be9c00d6d968958cf7f7ff20e6f82b210)
Reviewed-by: Jani Heikkinen <jani.heikkinen@qt.io>