Qt Linguist/qmake parser: Fix Unity build
Fix:
qttools/src/linguist/shared/parsers/qmakeparser.cpp:130:10: error: reference to ‘statics’ is ambiguous

Task-number: QTBUG-115448
Change-Id: Idd643e84ae4dd138c9a1d826916207890c94bb8f
Reviewed-by: Joerg Bornemann <joerg.bornemann@qt.io>
Reviewed-by: Masoud Jami <masoud.jami@qt.io>
(cherry picked from commit d7d0dd7a764d74ff3ed98339daf47b35dea1afd3)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>