Fix warning about ambiguous else (inside the foreach macro)
 messagemodel.cpp:435:12: error: suggest explicit braces to avoid ambiguous ‘else’ [-Werror=dangling-else]

Might as well change to range-for.

Change-Id: Id061f35c088044b69a15fffd15818f8a10e64064
Reviewed-by: Alessandro Portale <alessandro.portale@qt.io>