Assistant: Fix Werror=suggest-override warning
Fixes MinGW/gcc warning

  qttools/src/assistant/assistant/stdinlistener_win.h:49:10: error: 'virtual void StdInListener::run()' can be marked override [-Werror=suggest-override]

Change-Id: Id4be15e82811630ab26942c9d889abe1685e083a
Reviewed-by: Jarek Kobus <jaroslaw.kobus@qt.io>
(cherry picked from commit ad85ee214f9936b6a7b63762612dabc246d80866)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>