windeployqt: Fix build.
QCommandLineOption::setHidden() has been deprecated in 5.8:

main.cpp(354): error C2039: 'setHidden': is not a member of 'QCommandLineOption'

Change-Id: I9958de364b82502b41db62b5d6488263e8dfd934
Reviewed-by: Maurice Kalinowski <maurice.kalinowski@theqtcompany.com>
Reviewed-by: Oliver Wolff <oliver.wolff@theqtcompany.com>