QLayoutSupport: fix GCC 13 -Werror=overloaded-virtual
Says GCC 13:

  layoutdecoration.h:52:17: error: ‘virtual int Qt6::QDesignerLayoutDecorationExtension::findItemAt(int, int) const’ was hidden [-Werror=overloaded-virtual=]
     52 |     virtual int findItemAt(int row, int column) const = 0; // atm only for grid.
        |                 ^~~~~~~~~~
  qlayout_widget_p.h:178:16: note:   by ‘Qt6::qdesigner_internal::QLayoutSupport::findItemAt’
    178 |     static int findItemAt(QGridLayout *, int row, int column);
        |                ^~~~~~~~~~

Fix by adding the missing using declaration that brings
QDesignerLayoutDecorationExtension::findItemAt(int, int) into scope
again.

Pick-to: 6.5 6.4 6.2 5.15
Change-Id: I69b3033fa2da30388f87229cd2ab26822bab0d16
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@qt.io>