Fix build with QWebView as parent class for the help viewer
Using override with functions that are not virtual in the base causes
build errors such as

    error: ‘void HelpViewer::setSource(const QUrl&)’ marked override, but does not override

Change-Id: Ibdff5cdf199bb31810bbebf97d8f5ab2e6c777bf
Reviewed-by: Simon Hausmann <simon.hausmann@qt.io>