qdoc: Fix compile error about mixing different types in operator ?
Simplify code, fixing:

qdoc/generator.cpp: In member function QString Generator::fileName(const Node*, const QString&) const:
src/qdoc/qdoc/generator.cpp:361:31: error: operands to ?: have different types
   QStringBuilder<QString&, QString> and
   QStringBuilder<QString&, const QString&>

Change-Id: Ia986cb0b7c8811cc1adf186f1a2b5beb15667dc8
Reviewed-by: Fabian Kosmale <fabian.kosmale@qt.io>
(cherry picked from commit d221c18b5d797d0b665a44738748aca1fec62c86)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>