Fix warning about hidden overloaded virtual, found by Clang
qlayout_widget.cpp:1577:17: error: 'qdesigner_internal::<anonymous namespace>::QBoxLayoutSupport::findItemAt' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    virtual int findItemAt(int /*at_row*/, int /*at_column*/) const {    return -1; }
                ^
/Users/tjmaciei/src/qt/qt5/qttools/src/designer/src/lib/shared/qlayout_widget_p.h:198:17: note: hidden overloaded virtual function 'qdesigner_internal::QLayoutSupport::findItemAt' declared here
    virtual int findItemAt(const QPoint &pos) const;
                ^

Solve the problem by using the old functions, hence not hiding them.

Change-Id: I3af0c43fc7266ae74e8b05103e4306be740c618a
Reviewed-by: hjk <qthjk@ovi.com>
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@digia.com>