Designer: Mark methods as override
Fixes warnings with gcc on Windows:

  qdesigneraxwidget.h:70:11: error: 'virtual QSize QDesignerAxWidget::sizeHint() const' can be marked override [-Werror=suggest-override]

Change-Id: Ie2cb37d3afba14cd08edff090175495599219398
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@qt.io>
(cherry picked from commit c3c5b6f34fcc4a457c6b29373632705219a32763)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>