qhelpsearchindexwriter: fix compilation error
Remove the value from the return, the method does not return anything:

error: return-statement with a value, in function returning ‘void’
[-fpermissive]
  492 |                     return true;
      |                            ^~~~

Amends 405493a9b7a4b2a204be8bd16ca21cf9e8167f13.

Change-Id: Ia1ae914740d4a926c7e4459a85d6f649825d131b
Reviewed-by: Jarek Kobus <jaroslaw.kobus@qt.io>
(cherry picked from commit 492cd79d2c1b911714a0d074a8acb1879eb0adea)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>