Add missing #include for QDataStream
main.cpp:542:22: error: variable ‘QDataStream s’ has initializer but incomplete type
qm.cpp:236:16: error: ambiguous overload for ‘operator<<’ (operand types are ‘QDataStream’ and ‘quint8 {aka unsigned char}’)

Change-Id: Ie54f6b8e0362bb5d501a9ce58fd206d32fb3b697
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@digia.com>