Qt Linguist: Fix unity build error
Turn define EOL into a constant, fixing
a mixup with enum value EOL in qplatformdialoghelper.h:

qttools/src/linguist/shared/numerus.cpp:101:20: error: expected ‘}’ before ‘::’ token
  101 | #define EOL QLocale::C
      |                    ^~
In file included from install-qt-612/include/QtWidgets/6.12.1/QtWidgets/private/qdialog_p.h:27,
                 from /qttools/src/linguist/linguist/mainwindow.cpp:35,
                 from qttools/src/linguist/linguist/CMakeFiles/linguist.dir/Unity/unity_0_cxx.cxx:73:
                 include/QtGui/6.12.1/QtGui/qpa/qplatformdialoghelper.h:86:21: note: to match this ‘{’
   86 |     enum ButtonRole {
      |                     ^
/qttools/src/linguist/shared/numerus.cpp:101:20: error: invalid use of ‘::’
  101 | #define EOL QLocale::C

Task-number: QTBUG-115448
Change-Id: I546034512e728bad8636723aa976f2f3876a40c1
Reviewed-by: Masoud Jami <masoud.jami@qt.io>
(cherry picked from commit e6664b17ea062c67c7b90751cc57f68f1b0e0d02)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>