Add missing QPainterPath include
..\distancefieldmodel.h(197): error C2027: use of undefined type
'QPainterPath'

Change-Id: I3c97811a14bb82bf5dabc86398ffcfc9cf4ff58d
Reviewed-by: Andy Shaw <andy.shaw@qt.io>