Assistant: Fix static linking for Linux.
main.cpp:78: undefined reference to `qt_static_plugin_qsqlite()'

The import for the DB plugin should now be generated by qmake.

Change-Id: I9da25aea8667ca34221427236b8e1d36be77da8b
Reviewed-by: Oswald Buddenhagen <oswald.buddenhagen@digia.com>
Reviewed-by: Karsten Heimrich <karsten.heimrich@digia.com>
(cherry picked from commit f212e46fe930ee89a8cb52beeeccc03369c015a1)
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@digia.com>