QtCursorDatabase: Add missing QHash include
Fixes this build error seen in a -no-pch Clang 21 build:

    .../qt5/qttools/src/shared/qtpropertybrowser/qtpropertybrowserutils.cpp:36:29: error: implicit instantiation of undefined template 'QHash<Qt::CursorShape, const char *>'
       36 |     static const ShapeNames result =
          |                             ^
    .../qt5/qtbase/src/corelib/tools/qcontainerfwd.h:23:43: note: template is declared here
       23 | template <typename Key, typename T> class QHash;
          |                                           ^
    .../qt5/qttools/src/shared/qtpropertybrowser/qtpropertybrowserutils.cpp:196:36: error: implicit instantiation of undefined template 'QHash<Qt::CursorShape, const char *>'
      196 |     const char *name = shapeNames().value(shape, nullptr);
          |                                    ^
    .../qt5/qtbase/src/corelib/tools/qcontainerfwd.h:23:43: note: template is declared here
       23 | template <typename Key, typename T> class QHash;
          |                                           ^
    2 errors generated.
    ninja: build stopped: subcommand failed.

Amends c8d32bda682774553b01ab0dffe3a7371580d3b9.

Change-Id: I015b9ede74543626bffb53be28a8dea8cfdb4bbe
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@qt.io>
(cherry picked from commit 4d4fcdff46bb36e60660c28a48e365ba3792c8cb)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>